/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import com.toedter.calendar.JDateChooser;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author CRISTHIAN. S
 */
public class frmRegPaciente extends javax.swing.JInternalFrame {

    DefaultListModel ModeloLista;
    
    public frmRegPaciente() {
        initComponents();
        ModeloLista = new DefaultListModel();
        //listTelefonoP.setModel(ModeloLista);//Modifique el modelo de la listatelefono para acceder a los metodos del DefaultListModel
    }
    

    

    public JButton getBtnMunicipio() {
        return btnMunicipio;
    }

    public void setBtnMunicipio(JButton btnMunicipio) {
        this.btnMunicipio = btnMunicipio;
    }
    
    

    public JButton getBtnRegistrarP() {
        return btnRegistrarP;
    }

    public void setBtnRegistrarP(JButton btnRegistrarP) {
        this.btnRegistrarP = btnRegistrarP;
    }

    public JComboBox<String> getCmbTipoId() {
        return cmbTipoId;
    }

    public void setCmbTipoId(JComboBox<String> cmbTipoId) {
        this.cmbTipoId = cmbTipoId;
    }

    public JTextField getTxtTelefonoP1() {
        return txtTelefonoP1;
    }

    public void setTxtTelefonoP1(JTextField txtTelefonoP1) {
        this.txtTelefonoP1 = txtTelefonoP1;
    }

    public JTextField getTxtTelefonoP2() {
        return txtTelefonoP2;
    }

    public void setTxtTelefonoP2(JTextField txtTelefonoP2) {
        this.txtTelefonoP2 = txtTelefonoP2;
    }

  

    public JTextField getTxtIdP() {
        return txtIdP;
    }

    public void setTxtIdP(JTextField txtIdP) {
        this.txtIdP = txtIdP;
    }

    public JTextField getTxtMunicipioP() {
        return txtMunicipioP;
    }

    public void setTxtMunicipioP(JTextField txtMunicipioP) {
        this.txtMunicipioP = txtMunicipioP;
    }

    public JTextField getTxtNombreP() {
        return txtNombreP;
    }

    public void setTxtNombreP(JTextField txtNombreP) {
        this.txtNombreP = txtNombreP;
    }

    public JTextField getTxtTelefonoP() {
        return txtTelefonoP1;
    }

    public void setTxtTelefonoP(JTextField txtTelefonoP) {
        this.txtTelefonoP1 = txtTelefonoP;
    }

    public JDateChooser getDataFecha() {
        return DataFecha;
    }

    public void setDataFecha(JDateChooser DataFecha) {
        this.DataFecha = DataFecha;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdP = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMunicipioP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbTipoId = new javax.swing.JComboBox<String>();
        txtNombreP = new javax.swing.JTextField();
        btnRegistrarP = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTelefonoP1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        DataFecha = new com.toedter.calendar.JDateChooser();
        btnMunicipio = new javax.swing.JButton();
        txtTelefonoP2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Registro del paciente");

        jLabel2.setText("Numero de identficacion");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Registro del Paciente");

        jLabel4.setText("Tipo");

        jLabel5.setText("Municipio");

        txtMunicipioP.setEditable(false);

        jLabel1.setText("Nombre");

        cmbTipoId.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "T.I", "CC", "CE" }));

        btnRegistrarP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarP.setText("Registrar Paciente");
        btnRegistrarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPActionPerformed(evt);
            }
        });

        jLabel7.setText("Telefono(s)");

        txtTelefonoP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoP1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha de nacimiento");

        btnMunicipio.setText("Añadir Municipio");
        btnMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipioActionPerformed(evt);
            }
        });

        txtTelefonoP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoP2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Telefono(s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(txtNombreP))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefonoP1)
                                .addComponent(DataFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(txtTelefonoP2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMunicipioP, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMunicipio))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnRegistrarP)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbTipoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMunicipioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMunicipio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DataFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnRegistrarP)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoP1ActionPerformed

    private void btnMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMunicipioActionPerformed

    private void btnRegistrarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarPActionPerformed

    private void txtTelefonoP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoP2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DataFecha;
    private javax.swing.JButton btnMunicipio;
    private javax.swing.JButton btnRegistrarP;
    private javax.swing.JComboBox<String> cmbTipoId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtMunicipioP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtTelefonoP1;
    private javax.swing.JTextField txtTelefonoP2;
    // End of variables declaration//GEN-END:variables
}
